{"name":"feedback_throwsAValidationException_givenInvalidSourceData()","id":"[engine:junit-jupiter]/[class:be.sddevelopment.validation.ConstrainableTest]/[method:feedback_throwsAValidationException_givenInvalidSourceData()]","scenarioId":"[engine:junit-jupiter]/[class:be.sddevelopment.validation.ConstrainableTest]","testCaseName":"be.sddevelopment.validation.ConstrainableTest","methodName":"feedback_throwsAValidationException_givenInvalidSourceData","userStory":{"id":"be.sddevelopment.validation.ConstrainableTest","storyName":"ConstrainableTest","displayName":"ConstrainableTest","storyClassName":"be.sddevelopment.validation.ConstrainableTest","path":"ConstrainableTest","pathElements":[{"name":"ConstrainableTest","description":"ConstrainableTest"}],"narrative":"","type":"feature"},"title":"Feedback throws a validation exception given invalid source data","tags":[{"name":"ConstrainableTest","type":"feature","displayName":"ConstrainableTest"}],"startTime":"2023-12-28T06:25:24.158574968+01:00[Europe/Brussels]","duration":4,"projectKey":"","driver":"","isManualTestingUpToDate":false,"manual":false,"testSource":"JUnit5","order":0,"result":"SUCCESS"}